### ISSUE TITLE
Output table in Markdown format

### ISSUE THREAD

**Issue by cwellsx** [wyhaya/lok#1]
A neat extra feature could be to output the table in [GitHub Markdown table format](https://help.github.com/en/articles/organizing-information-with-tables) (instead of ASCII graphics).

That could look better, if it's then converted from Markdown to HTML, and/or if it's copied-and-pasted into a Markdown document.

**Comment by wyhaya** [comment]
Output markdown and html formats are now supported.
```bash
lok -o html > code.html
lok -o markdown > code.md
```
