### ISSUE TITLE
What happened to the commit history?

### ISSUE THREAD

**Issue by mmahmoudian** [wyhaya/lok#6]
The commits history only shows commits since 2022-05-09 and the first commit is a complete rewrite, where in fact this project is few years old. I wonder why this has happened.

**Comment by wyhaya** [comment]
The tool was originally written in [Node.js](https://nodejs.org/zh-cn/) and later rewritten in `Rust`, and although all the code is no longer related to `Node.js`, `GitHub` kept sending me some security warnings from `node modules`, and I finally chose to clear the commit history, and now everything is fine.
